# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("useConfetti works", {
  expect_true(inherits(useConfetti, "function"))
  dep <- useConfetti()
  expect_false(is.null(dep))
  expect_equal(dep[["name"]], "canvas-confetti")
  expect_true(length(dep[["script"]]) >= 1)
})
