# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

test_that("sendfireworks works", {
  library(shinytest2)
  
  app <- shinytest2::AppDriver$new(
    system.file("shiny", "test", "fireworks", "app.R", package = "confetti")
  )
  expect_equal(app$get_value(input = "go")[[1]], 0)
  expect_equal(app$get_value(input = "sentFireworks"), 0)
  
  app$click("go")
  html <- app$get_html("canvas")
  
  expect_equal(app$get_value(input = "go")[[1]], 1)
  expect_equal(app$get_value(input = "sentFireworks"), 1)
  expect_equal(app$get_value(input = "sentConfetti"), 0)
  
  app$click("go")
  expect_equal(app$get_value(input = "go")[[1]], 2)
  expect_equal(app$get_value(input = "sentFireworks"), 2)
  expect_equal(app$get_value(input = "sentConfetti"), 0)
})
