# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

#' sendfireworks
#' 
#' Send fireworks in your shiny app
#' 
#' @param duration Number. Fireworks duration in seconds
#' @param particle_count Number. How many confetti launch. Default is 50.
#' @param colors List. A list of color strings, in the HEX format.
#' @param shapes List. A list of shapes for the confetti. Square or circle.
#' @param session a shiny session
#' 
#' @importFrom shiny getDefaultReactiveDomain
#'
#' @return a javascript event in a shiny app to launch confetti.
#' @export
#' @examples
#' if (interactive()) {
#'   library(shiny)
#'
#'   if (shinytest2:::on_ci() && shinytest2:::is_windows()) {
#'     testthat::skip()
#'   }
#'   
#'   shinyApp(
#'     ui = fluidRow(
#'       useConfetti(),
#'       actionButton(
#'         inputId = "go",
#'         label =  "Send fireworks"
#'       )
#'     ),
#'     
#'     server = function(input, output, session) {
#'       observeEvent(input$go, {
#'         sendfireworks(
#'           duration = 5,
#'           colors = list("#DAB436", "#36DA62", "#365CDA")
#'         )
#'         message("You have sent ", input$sentFireworks, " fireworks")
#'         message("You have sent ", input$sentConfetti, " confetti")
#'       })
#'     }
#'   )
#' }
sendfireworks <- function(duration,
                         particle_count = 50,
                         colors = NA,
                         shapes = NA,
                         session = shiny::getDefaultReactiveDomain()) {
  
  session$sendCustomMessage(
    "send.fireworks",
    list(
      duration = duration,
      particle_count = particle_count,
      colors = colors,
      shapes = shapes
    )
  )
}
