# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' useConfetti
#' 
#' create an html dependency to a Shiny app
#' 
#' @importFrom htmltools htmlDependency
#' 
#' @return a html_dependency
#' @export
#' 
#' @examples
#' useConfetti()
useConfetti <- function() {
  htmlDependency(
    name = "canvas-confetti",
    version = "1.5.1",
    src = system.file("www", "canvas-confetti-1.5.1", package = "confetti"),
    script = c(
      "confetti.browser.min.js",
      "handlers.js"
    )
  )
}
